# Configuration file for hypersonic reentry trajectory optimization

# Vehicle parameters
vehicle:
  mass: 5000.0  # kg
  reference_area: 15.0  # m^2
  drag_coefficient: 1.2
  lift_coefficient: 0.8
  nose_radius: 0.5  # m
  ballistic_coefficient: 400.0  # kg/m^2

# Initial conditions
initial_conditions:
  altitude: 120000.0  # m
  velocity: 7800.0    # m/s
  flight_path_angle: -1.5  # degrees
  latitude: 28.5      # degrees
  longitude: -80.6    # degrees
  azimuth: 90.0       # degrees

# Target conditions
target_conditions:
  altitude_final: 30000.0  # m
  velocity_final: 300.0    # m/s
  downrange_max: 2000000.0 # m
  crossrange_max: 200000.0 # m

# Atmosphere model parameters
atmosphere:
  model_type: "us_standard_1976"
  density_uncertainty: 0.15  # 15% standard deviation
  temperature_uncertainty: 0.05  # 5% standard deviation
  wind_uncertainty: 50.0  # m/s standard deviation

# Optimization parameters
optimization:
  method: "gradient_based"  # or "evolutionary" or "hybrid"
  max_iterations: 1000
  tolerance: 1e-6
  population_size: 100  # for evolutionary methods
  crossover_rate: 0.8
  mutation_rate: 0.1

# Uncertainty quantification
uncertainty:
  method: "monte_carlo"  # or "polynomial_chaos" or "stochastic_collocation"
  samples: 10000
  confidence_level: 0.95
  seed: 42

# Control system
control:
  controller_type: "lqr"  # or "mpc" or "adaptive"
  update_frequency: 10.0  # Hz
  bank_angle_limits: [-60.0, 60.0]  # degrees
  angle_of_attack_limits: [0.0, 40.0]  # degrees

# Simulation parameters
simulation:
  time_step: 0.1  # seconds
  max_time: 3000.0  # seconds
  integration_method: "rk45"
  absolute_tolerance: 1e-9
  relative_tolerance: 1e-6

# Visualization settings
visualization:
  save_plots: true
  plot_format: "png"
  dpi: 300
  figure_size: [12, 8]
  color_scheme: "viridis"
  interactive: true

# Output settings
output:
  results_directory: "results"
  save_trajectory_data: true
  save_statistics: true
  generate_report: true
  export_formats: ["hdf5", "csv", "json"]